#!/bin/sh

BUILD_DIR="$1"
TAG="$2"

URL=`svn info "${BUILD_DIR}" | awk '/URL/ { print $2; }'`
REVISION=`svn info "${BUILD_DIR}" | awk '/Revision/ { print $2; }'`

echo "LABEL svnurl=${URL} svnrevision=${REVISION}" >>"${BUILD_DIR}/Dockerfile"
