#!/bin/sh

BUILD_DIR="$1"
TAG="$2"

URL=`svn info "${BUILD_DIR}" | awk '/URL/ { print $2; }'` svnrevision=`
REVISION=`svnversion "${BUILD_DIR}"`

echo "LABEL svnurl=${URL} svnrevision=${REVISION}" >>Dockerfile
